language: python
python:
  - 3.6

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
  matrix:
    - TOXENV=py36
    - TOXENV=flake8
    - TOXENV=docs
  
before_install:
  - sudo .ci/travis-before-install.sh

install:
  - .ci/travis-install.sh

before_script:
  - .ci/travis-before-script.sh

script: .ci/travis_script.sh

after_success:
  - .ci/travis-after-success.sh
